name: Testes Vital Clinic

on:
  push:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring

      - name: Verificar versão do PHP
        run: php -v

      - name: Teste de Login
        run: php tests/tests_auth.php

      - name: Teste de Recuperação de Senha
        run: php tests/tests_recovery.php

      - name: Teste de Médicos
        run: php tests/tests_medicos.php

      - name: Teste de Pacientes
        run: php tests/tests_pacientes.php

      - name: Teste de Consultas
        run: php tests/tests_consultas.php

      - name: Gerar artefato do projeto
        run: |
          zip -r VitalClinic.zip VitalClinic
          
      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: VitalClinic
          path: VitalClinic.zip